import Head from "next/head";
import Sidebar from "../../components/Sidebar";
import Widgets from "../../components/Widgets";
import CommentModal from "../../components/CommentModal";

import { useRouter } from "next/router";
import { ArrowLeftIcon } from "@heroicons/react/24/outline";
import Post from "../../components/Post";
import { useEffect, useState } from "react";
import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import { db } from "../../firebase";
import Comment from "../../components/Comment";
import { AnimatePresence, motion } from "framer-motion";

const PostPage = ({ newsArticle, randomUsersResults }) => {
  const router = useRouter();
  const [post, setPost] = useState(null);
  const [comments, setComments] = useState([]);
  const { postId } = router.query;

  useEffect(() => {
    onSnapshot(doc(db, "posts", postId), (doc) => {
      setPost(doc);
    });
  }, [postId]);

  // Get comments of the post
  useEffect(() => {
    onSnapshot(
      query(
        collection(db, "posts", postId, "comments"),
        orderBy("timestamp", "desc")
      ),
      (snapshot) => {
        setComments(snapshot.docs);
      }
    );
  }, [postId]);

  return (
    <>
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-between min-h-screen mx-auto">
        <Sidebar />

        <div className="xl:ml-[370px] border-l border-r border-gray-200 xl:min-w-[576px] sm:ml-[75px] flex-grow max-w-xl">
          <div className="flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
            <div
              className="hoverEffect flex items-center justify-center"
              onClick={() => router.push("/")}
            >
              <ArrowLeftIcon className="h-5" />
            </div>

            <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
              Tweet
            </h2>
          </div>

          {post && <Post post={post} />}

          {comments.length > 0 && (
            <AnimatePresence>
              {comments.map((comment) => (
                <motion.div
                  key={comment.id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 1 }}
                >
                  <Comment
                    commentId={comment.id}
                    originalPostId={postId}
                    comment={comment.data()}
                  />
                </motion.div>
              ))}
            </AnimatePresence>
          )}
        </div>

        <Widgets
          newsArticle={newsArticle.articles}
          randomUsersResults={randomUsersResults.results}
        />

        <CommentModal />
      </main>
    </>
  );
};

export default PostPage;

export const getServerSideProps = async () => {
  const res = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  );
  const newsArticle = await res.json();

  const followRes = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  );

  const randomUsersResults = await followRes.json();

  return {
    props: {
      newsArticle,
      randomUsersResults,
    },
  };
};

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

/* {posts.map((post) => (
              <motion.div
                key={post.id}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 1 }}
              >
                <Post post={post} />
              </motion.div>
            ))} */
