import Head from "next/head";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";

export default function Home({ newsResults }) {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        <Sidebar />

        <Feed />

        <Widgets newsResults={newsResults.articles} />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  );
  const newsResults = await res.json();

  return {
    props: {
      newsResults,
    },
  };
};

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
